# Minimal Configuration Example
# Single agent setup for quick testing

app:
  title: "AI Agent System - Minimal"
  version: "2.0.0"
  frontend_url: "${FRONTEND_URL:*}"
  log_level: "${LOG_LEVEL:INFO}"
  host: "0.0.0.0"
  port: 8000

agents:
  assistant:
    type: "generic"
    enabled: true
    instructions: "You are a helpful AI assistant. Provide clear and concise responses."
    metadata:
      description: "General purpose assistant"
      capabilities: ["conversation", "help"]
    framework_config:
      provider: "azure_openai"
      model: "gpt-4o"
      temperature: 0.7
      max_tokens: 1000

router:
  type: "pattern"
  fallback_to_llm: false
  patterns:
    assistant:
      - ".*"  # Match everything

session:
  storage_type: "memory"
  max_sessions: 100
  session_timeout: 1800