# Development Configuration
# Development-friendly settings with debugging enabled

app:
  title: "AI Agent System - Development"
  version: "2.0.0-dev"
  frontend_url: "${FRONTEND_URL:*}"  # Allow all origins in dev
  log_level: "${LOG_LEVEL:DEBUG}"    # Verbose logging
  host: "0.0.0.0"
  port: 8000

agents:
  dev_assistant:
    type: "generic"
    enabled: true
    instructions: "You are a development AI assistant. Help with coding, debugging, and development questions. Be detailed in your explanations."
    metadata:
      description: "Development assistant"
      capabilities: ["coding_help", "debugging", "development_support"]
    framework_config:
      provider: "azure_openai"
      model: "gpt-4o"
      temperature: 0.7
      max_tokens: 1500  # Longer responses for dev
      timeout: 60

  test_agent:
    type: "generic"
    enabled: true
    instructions: "You are a test agent for development purposes. Feel free to experiment and try different responses."
    metadata:
      description: "Test and experimentation agent"
      capabilities: ["testing", "experimentation"]
    framework_config:
      provider: "azure_openai"
      model: "gpt-4o-mini"  # Cheaper model for testing
      temperature: 0.8
      max_tokens: 500

  debug_helper:
    type: "knowledge_finder"
    enabled: false  # Disabled by default, enable for debugging
    instructions: "You are a debugging specialist. Help identify and solve problems. Provide step-by-step debugging guidance."
    metadata:
      description: "Debugging and troubleshooting specialist"
      capabilities: ["debugging", "troubleshooting", "problem_solving"]
    framework_config:
      provider: "azure_openai"
      model: "gpt-4o"
      temperature: 0.3
      max_tokens: 1200

router:
  type: "pattern"  # Simpler routing for development
  fallback_to_llm: false
  patterns:
    dev_assistant:
      - ".*code.*"
      - ".*develop.*"
      - ".*programming.*"
      - ".*debug.*"
    test_agent:
      - ".*test.*"
      - ".*experiment.*"
      - ".*try.*"
    debug_helper:
      - ".*problem.*"
      - ".*error.*"
      - ".*troubleshoot.*"
      - ".*fix.*"

session:
  storage_type: "file"  # Persistent but simple
  file_path: "./dev_sessions"
  max_sessions: 50      # Limited for development
  session_timeout: 1800 # 30 minutes

# Development-specific settings
dev_settings:
  auto_reload: true
  debug_mode: true
  verbose_errors: true
  cors_allow_all: true
  disable_auth: true