# Modern LangChain Agent System Configuration

# Application settings
app:
  title: "LangChain AI Agent System"
  version: "2.0.0"
  frontend_url: "${FRONTEND_URL:*}"
  log_level: "${LOG_LEVEL:INFO}"
  environment: "${ENVIRONMENT:production}"

# Azure OpenAI configuration
azure_openai:
  endpoint: "${AZURE_OPENAI_ENDPOINT}"
  api_key: "${AZURE_OPENAI_API_KEY}"
  api_version: "${AZURE_OPENAI_API_VERSION:2024-02-01}"
  deployment_name: "${AZURE_OPENAI_DEPLOYMENT_NAME:gpt-4o-mini}"

# Azure AI Foundry project configuration
azure_foundry:
  project_endpoint: "${PROJECT_ENDPOINT}"
  people_agent_id: "${PEOPLE_AGENT_ID}"
  knowledge_agent_id: "${KNOWLEDGE_AGENT_ID}"

# Session management
sessions:
  storage_type: "${SESSION_STORAGE_TYPE:file}"  # memory, file, redis
  storage_path: "${SESSION_STORAGE_PATH:./sessions}"
  redis_url: "${REDIS_URL:}"
  cleanup_interval_hours: 24
  max_age_days: 7

# Caching
cache:
  enabled: true
  max_size: 1000
  ttl_seconds: 3600

# Logging and monitoring
logging:
  level: "${LOG_LEVEL:INFO}"
  format: "structured"
  enable_debug: "${DEBUG_LOGS:0}"

# Agent configurations
agents:
  generic_agent:
    type: "generic"
    enabled: true
    instructions: |
      You are a helpful AI assistant. Provide accurate, concise, and helpful responses to user questions.
      Be friendly and professional in your interactions. If you're unsure about something, say so rather than guessing.
    metadata:
      description: "General purpose conversational agent"
      capabilities: ["general_conversation", "information_retrieval", "task_assistance"]
    framework_config:
      model: "${GENERIC_MODEL:gpt-4o-mini}"
      temperature: 0.7
      max_tokens: 1000

  people_lookup:
    type: "people_lookup"
    enabled: true
    instructions: |
      You are a people lookup specialist. Help users find information about people in the organization including:
      - Contact details (email, phone)
      - Organizational hierarchy (manager, reports)
      - Team membership and roles
      - Location and department information
      
      Always be respectful of privacy and only share appropriate business information.
    metadata:
      description: "Finds information about people in the organization"
      capabilities: ["employee_search", "contact_lookup", "org_chart", "team_info"]
    framework_config:
      agent_id: "${PEOPLE_AGENT_ID}"
      project_endpoint: "${PROJECT_ENDPOINT}"

  knowledge_finder:
    type: "knowledge_finder"
    enabled: true
    instructions: |
      You are a knowledge and documentation specialist. Help users find information about:
      - Company policies and procedures
      - Technical documentation
      - Product information and guides
      - Best practices and how-to guides
      - Platform-specific information (Akumina, etc.)
      
      Provide accurate, up-to-date information and cite sources when possible.
    metadata:
      description: "Searches documentation and knowledge bases"
      capabilities: ["document_search", "policy_lookup", "technical_support", "procedure_guidance"]
    framework_config:
      agent_id: "${KNOWLEDGE_AGENT_ID}"
      project_endpoint: "${PROJECT_ENDPOINT}"

# Router configuration
router:
  type: "hybrid"  # pattern, llm, hybrid
  fallback_to_llm: true
  history_weight: 0.3
  
  # Routing patterns for pattern-based routing
  patterns:
    people_lookup:
      - "\\b(who is|find|lookup|contact)\\b.*\\b(person|employee|user|staff)\\b"
      - "\\b(manager|supervisor|lead|director)\\b"
      - "\\bemail.*@\\b"
      - "\\bphone.*number\\b"
      - "\\b(team|department|organization)\\b"
    
    knowledge_finder:
      - "\\b(how to|procedure|process|guide|documentation)\\b"
      - "\\b(policy|guideline|standard|requirement)\\b"
      - "\\b(setup|configuration|install|deploy)\\b"
      - "\\b(akumina|platform|technical)\\b"
      - "\\b(manual|tutorial|instruction)\\b"

  # LLM routing prompt
  llm_prompt: |
    You are an agent router. Read the user's message and pick exactly ONE agent to answer.

    Agents:
      - people_lookup: Finds information about specific people (name/role/email/manager/phone/team/employee details).
      - knowledge_finder: Answers questions based on documentation, policies, product/technical info, and internal how-tos.
      - generic_agent: General knowledge and chit-chat (cities, weather, general topics not specific to organization or a person).

    Rules:
      - Return EXACTLY one of: people_lookup | knowledge_finder | generic_agent
      - Output ONLY the label — no punctuation, no explanation, no quotes.
      - If the request is about a specific person (identity, contact, org info), choose people_lookup.
      - If the request is about documentation/policies/product/tech details/how-to, choose knowledge_finder.
      - Otherwise choose generic_agent.
      - If uncertain, choose generic_agent.

    Examples:
      Q: "Write about Boston" -> generic_agent
      Q: "Get me the details of John" -> people_lookup
      Q: "What is our PIM approval flow?" -> knowledge_finder
      Q: "Show the mobile app Intune setup steps" -> knowledge_finder
      Q: "Who is Jane Doe from Sales?" -> people_lookup

    Available agents: {available_agents}

    User message:
    {message}

# Health checks
health:
  enabled: true
  check_interval_seconds: 30
  timeout_seconds: 10

# Security (future enhancement)
security:
  enable_auth: false
  api_key_header: "X-API-Key"
  rate_limit_requests: 100
  rate_limit_window_seconds: 60

# Group Chat configurations
group_chats:
  # Default group chat templates
  templates:
    marketing_team:
      name: "Marketing Strategy Session"
      description: "Marketing team collaboration on campaigns and strategy"
      max_turns: 8
      auto_select_speaker: true
      participants:
        - name: "MarketingManager"
          instructions: "You are a marketing manager. Focus on campaign strategies, target audiences, and brand positioning."
          role: "facilitator"
          priority: 3
        - name: "DataAnalyst"
          instructions: "You are a data analyst. Focus on metrics, analytics, and data-driven insights for marketing decisions."
          role: "participant"
          priority: 2
        - name: "CreativeDirector"
          instructions: "You are a creative director. Focus on content creation, visual design, and creative campaign ideas."
          role: "participant"
          priority: 2

    technical_architecture:
      name: "Technical Architecture Review"
      description: "Expert review of system architecture with LangChain intelligence"
      max_turns: 6
      auto_select_speaker: true
      participants:
        - name: "CloudArchitect"
          instructions: "You are a cloud architect specializing in AWS and Azure. Focus on scalability, reliability, and cloud best practices."
          role: "participant"
          priority: 2
        - name: "SecurityArchitect"
          instructions: "You are a security architect. Focus on security threats, compliance, data protection, and secure design patterns."
          role: "participant"
          priority: 2
        - name: "SystemsEngineer"
          instructions: "You are a systems engineer. Focus on system integration, monitoring, observability, and operational concerns."
          role: "facilitator"
          priority: 3

    project_planning:
      name: "Project Planning Meeting"
      description: "Cross-functional project planning with intelligent speaker selection"
      max_turns: 10
      auto_select_speaker: true
      participants:
        - name: "ProjectManager"
          instructions: "You are a project manager. Keep discussions focused, track timelines, and ensure deliverables are clear."
          role: "facilitator"
          priority: 3
        - name: "TechLead"
          instructions: "You are a technical lead. Assess technical feasibility and provide implementation guidance."
          role: "participant"
          priority: 2
        - name: "BusinessAnalyst"
          instructions: "You are a business analyst. Focus on requirements gathering and business value assessment."
          role: "participant"
          priority: 2
